explainer_task:
  description: >
    You are provided with a news item containing the following fields:

    • Title: {title}
    • Description: {description}
    • Content: {content}

    Your task is to generate a clear and informative summary of the article based strictly on these inputs.

    Guidelines:
    1. Use only the provided fields—do not retrieve or assume any external information.
    2. If description and content are missing or insufficient, rely on your internal understanding of the title.
    3. Write a well-structured summary consisting of exactly 8 to 10 complete sentences.
    4. Paraphrase and reorganize the input; do not copy or echo it verbatim.
    5. Ensure the summary is coherent, factual, and easy to understand for a general audience.
    6. Adopt the tone of a professional news reporter delivering the information directly to an audience.
       Avoid saying "the article says" or "the article discusses"—instead, present the information as if you
       are reporting it live.

  expected_output: >
    A clean, 8–10 sentence news report-style summary, written entirely from the provided inputs.

    Do NOT:
    - Include tool output, internal thoughts, or reasoning.
    - Write confirmation phrases such as:
      - "I now can give a great answer"
      - "Here's your summary"
      - "This is the cleaned version"
      - "I can now proceed"
    - Echo the input text verbatim.
    - Refer to the source as "the article" or "this piece".

    Only return the final news-style summary in complete, professional sentences—ready for display or broadcast.
  agent: explainer_agent

keyword_extractor_task:
  description: >
    You are provided with a user query intended to search for relevant news articles.

    Your task is to extract the most meaningful keywords from the query to improve search accuracy 
    when interacting with a news API or database.

    Guidelines:
    1. Do NOT rephrase or summarize the query—your job is only to extract keywords.
    2. Remove all stop words, filler phrases, and general-purpose verbs.
    3. Retain proper nouns, entities, topic-specific nouns, and crucial modifiers.
    4. Return the keywords as a comma-separated list (no bullet points or full sentences).
    5. Maintain a balance—return between 3 and 8 relevant keywords.
    6. If the query is vague or generic, extract the most probable core topics.

    Query: {query}

  expected_output: >
    A clean, comma-separated list of relevant keywords extracted from the input query.

    Do NOT:
    - Rephrase or summarize the original query.
    - Output full sentences or explanations.
    - Include "Keywords:" or similar labels.
    - Include more than 8 or fewer than 3 keywords.

    Only return the final keyword string, optimized for direct use in a search query or API request.

  agent: keyword_extractor_agent
