explainer_task:
  description: >
    You are provided with a news item containing the following fields:

    • Title: {title}
    • Description: {description}
    • Content: {content}

    Your task is to generate a clear and informative summary of the article based strictly on these inputs.

    Guidelines:
    1. Use only the provided fields—do not retrieve or assume any external information.
    2. If description and content are missing or insufficient, rely on your internal understanding of the title.
    3. Write a well-structured summary consisting of exactly 8 to 10 complete sentences.
    4. Paraphrase and reorganize the input; do not copy or echo it verbatim.
    5. Ensure the summary is coherent, factual, and easy to understand for a general audience.
    6. Adopt the tone of a professional news reporter delivering the information directly to an audience.
       Avoid saying "the article says" or "the article discusses"—instead, present the information as if you
       are reporting it live.

  expected_output: >
    A clean, 8–10 sentence news report-style summary, written entirely from the provided inputs.

    Do NOT:
    - Include tool output, internal thoughts, or reasoning.
    - Write confirmation phrases such as:
      - "I now can give a great answer"
      - "Here's your summary"
      - "This is the cleaned version"
      - "I can now proceed"
    - Echo the input text verbatim.
    - Refer to the source as "the article" or "this piece".

    Only return the final news-style summary in complete, professional sentences—ready for display or broadcast.
  agent: explainer_agent
